//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('currencies')
export class currenciesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  CurrencyID: number;

  @Column('text', { nullable: true })
  CurrencyName: string;

  @Column('text', { nullable: true })
  CurrencyCode: string;

  @Column('text', { nullable: true })
  Symbol: string;

  @Column('text', { nullable: true })
  Country: string;

  @Column('real', { nullable: true })
  ExchangeRate: number;
}
