//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('PaymentMethods')
export class PaymentMethodsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  PaymentMethodID: number;

  @Column('text', { nullable: true })
  PaymentMethodName: string;

  @Column('text', { nullable: true })
  Provider: string;

  @Column('text', { nullable: true })
  AccountDetails: string;

  @Column('integer', { nullable: true })
  UserID: number;

  @Column('date', { nullable: true })
  ExpiryDate: Date;

  @Column('text', { nullable: true })
  Status: string;
}
