//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('transactions')
export class transactionsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  TransactionID: number;

  @Column('integer', { nullable: true })
  UserID: number;

  @Column('integer', { nullable: true })
  CurrencyFrom: number;

  @Column('integer', { nullable: true })
  CurrencyTo: number;

  @Column('real', { nullable: true })
  AmountSent: number;

  @Column('real', { nullable: true })
  AmountReceived: number;

  @Column('date', { nullable: true })
  TransactionDate: Date;

  @Column('real', { nullable: true })
  ExchangeRate: number;

  @Column('text', { nullable: true })
  Status: string;
}
