//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const PaymentMethodsTitle = () => {
  const record = useRecordContext();
  return (
    <span>PaymentMethods {record ? `"${record.PaymentMethodID}"` : ''}</span>
  );
};

export const PaymentMethodsList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <NumberField source="PaymentMethodID" />
      <TextField source="PaymentMethodName" />
      <TextField source="Provider" />
      <ReadOnlyPasswordField source="AccountDetails" />
      <ReferenceField source="UserID" reference="users" />
      <DateField source="ExpiryDate" />
      <TextField source="Status" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const PaymentMethodsEdit = () => (
  <Edit title={<PaymentMethodsTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <NumberInput source="PaymentMethodID" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="PaymentMethodName" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Provider" />
        </Grid>
        <Grid item xs={4}>
          <PasswordInput source="AccountDetails" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="UserID" reference="users" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="ExpiryDate" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Status" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const PaymentMethodsCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <NumberInput source="PaymentMethodID" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="PaymentMethodName" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Provider" />
        </Grid>
        <Grid item xs={4}>
          <PasswordInput source="AccountDetails" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="UserID" reference="users" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="ExpiryDate" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Status" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  ,
  ,
  ,
  <ReferenceInput source="UserID" label="UserID" reference="users" alwaysOn />,
  ,
  ,
];
