//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const transactionsTitle = () => {
  const record = useRecordContext();
  return <span>transactions {record ? `"${record.TransactionID}"` : ''}</span>;
};

export const transactionsList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <NumberField source="TransactionID" />
      <ReferenceField source="UserID" reference="users" />
      <ReferenceField source="CurrencyFrom" reference="currencies" />
      <ReferenceField source="CurrencyTo" reference="currencies" />
      <NumberField source="AmountSent" />
      <NumberField source="AmountReceived" />
      <DateField source="TransactionDate" />
      <NumberField source="ExchangeRate" />
      <TextField source="Status" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const transactionsEdit = () => (
  <Edit title={<transactionsTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <NumberInput source="TransactionID" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="UserID" reference="users" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="CurrencyFrom" reference="currencies" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="CurrencyTo" reference="currencies" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="AmountSent" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="AmountReceived" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="TransactionDate" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="ExchangeRate" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Status" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const transactionsCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <NumberInput source="TransactionID" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="UserID" reference="users" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="CurrencyFrom" reference="currencies" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="CurrencyTo" reference="currencies" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="AmountSent" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="AmountReceived" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="TransactionDate" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="ExchangeRate" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Status" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  <ReferenceInput source="UserID" label="UserID" reference="users" alwaysOn />,
  <ReferenceInput
    source="CurrencyFrom"
    label="CurrencyFrom"
    reference="currencies"
    alwaysOn
  />,
  <ReferenceInput
    source="CurrencyTo"
    label="CurrencyTo"
    reference="currencies"
    alwaysOn
  />,
  ,
  ,
  ,
  ,
  ,
];
