//Source code generated by AppGPT (www.appgpt.tech)
import { Admin, Resource, CustomRoutes } from 'react-admin';
import { customDataProvider } from './dataProvider';
import fakeDataProvider from 'ra-data-fakerest';
import { Dashboard } from './dashboard';
import { authProvider, apInitialize } from './authProvider';
import { i18nProvider } from './i18nProvider';
import LoginPage, { Login } from './Login';
import data from './data';
import {
  transactionsList,
  transactionsCreate,
  transactionsEdit,
} from './resources/transactions';
import { usersList, usersCreate, usersEdit } from './resources/users';
import {
  currenciesList,
  currenciesCreate,
  currenciesEdit,
} from './resources/currencies';
import {
  PaymentMethodsList,
  PaymentMethodsCreate,
  PaymentMethodsEdit,
} from './resources/PaymentMethods';
import transactionsIcon from '@mui/icons-material/Payment';
import usersIcon from '@mui/icons-material/People';
import currenciesIcon from '@mui/icons-material/AttachMoney';
import PaymentMethodsIcon from '@mui/icons-material/Payment';
// SUPERTOKENS
import React from 'react';
import SuperTokens, {
  SuperTokensWrapper,
  getSuperTokensRoutesForReactRouterDom,
} from 'supertokens-auth-react';
import ThirdPartyPasswordless from 'supertokens-auth-react/recipe/thirdpartypasswordless';
import Session from 'supertokens-auth-react/recipe/session';
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';
import * as reactRouterDom from 'react-router-dom';
let sessionFn = Session.init();
SuperTokens.init({
  appInfo: {
    appName: import.meta.env.VITE_SUPERTOKENS_APPNAME,
    apiDomain: import.meta.env.VITE_BACKEND_DOMAIN,
    websiteDomain: import.meta.env.VITE_SUPERTOKENS_WEBSITEDOMAIN,
    apiBasePath: import.meta.env.VITE_BACKEND_APIPATH + '/auth',
    websiteBasePath: import.meta.env.VITE_SUPERTOKENS_WEBSITEBASEPATH,
  },
  recipeList: [
    ThirdPartyPasswordless.init({
      contactMethod: 'EMAIL',
      signInUpFeature: {
        providers: [
          ThirdPartyPasswordless.Github.init(),
          //ThirdPartyPasswordless.Google.init(),
          //ThirdPartyPasswordless.Facebook.init(),
          //ThirdPartyPasswordless.Apple.init(),
        ],
      },
    }),
    sessionFn,
  ],
});
apInitialize(Session);
// END SUPERTOKENS
let dataProvider: any;
if (import.meta.env.VITE_USE_BACKEND_DATA === 'true') {
  dataProvider = customDataProvider(
    import.meta.env.VITE_BACKEND_DOMAIN +
      import.meta.env.VITE_BACKEND_APIPATH +
      '/proxy',
  );
} else {
  dataProvider = fakeDataProvider(data.defaultData);
}

const App = () => (
  <SuperTokensWrapper>
    <BrowserRouter basename="/af5a78855">
      <Admin
        authProvider={
          import.meta.env.VITE_ENVIRONMENT != 'DEV' ? authProvider : undefined
        }
        requireAuth
        loginPage={LoginPage}
        dataProvider={dataProvider}
        i18nProvider={i18nProvider}
        dashboard={Dashboard}
      >
        <Resource
          name="transactions"
          options={{ label: 'Transactions' }}
          list={transactionsList}
          create={transactionsCreate}
          edit={transactionsEdit}
          recordRepresentation="TransactionID"
          icon={transactionsIcon}
        />
        <Resource
          name="users"
          options={{ label: 'Users' }}
          list={usersList}
          create={usersCreate}
          edit={usersEdit}
          recordRepresentation="UserID"
          icon={usersIcon}
        />
        <Resource
          name="currencies"
          options={{ label: 'Currencies' }}
          list={currenciesList}
          create={currenciesCreate}
          edit={currenciesEdit}
          recordRepresentation="CurrencyID"
          icon={currenciesIcon}
        />
        <Resource
          name="PaymentMethods"
          options={{ label: 'Payment Methods' }}
          list={PaymentMethodsList}
          create={PaymentMethodsCreate}
          edit={PaymentMethodsEdit}
          recordRepresentation="PaymentMethodID"
          icon={PaymentMethodsIcon}
        />
        <CustomRoutes noLayout>
          {/*This renders the login UI on the /auth route*/}
          {getSuperTokensRoutesForReactRouterDom(reactRouterDom)}
          {/*Your app routes*/}
        </CustomRoutes>
      </Admin>
    </BrowserRouter>
  </SuperTokensWrapper>
);

export default App;
