//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    transactions: {
      name: 'Transactions',
      fields: {
        TransactionID: 'Transaction Id',
        UserID: 'User Id',
        CurrencyFrom: 'Currency From',
        CurrencyTo: 'Currency To',
        AmountSent: 'Amount Sent',
        AmountReceived: 'Amount Received',
        TransactionDate: 'Transaction Date',
        ExchangeRate: 'Exchange Rate',
        Status: 'Status',
        id: 'id',
      },
    },
    users: {
      name: 'Users',
      fields: {
        UserID: 'User Id',
        Username: 'Username',
        Email: 'Email',
        Password: 'Password',
        FullName: 'Full Name',
        RegistrationDate: 'Registration Date',
        LastLoginDate: 'Last Login Date',
        AccountStatus: 'Account Status',
        id: 'id',
      },
    },
    currencies: {
      name: 'Currencies',
      fields: {
        CurrencyID: 'Currency Id',
        CurrencyName: 'Currency Name',
        CurrencyCode: 'Currency Code',
        Symbol: 'Symbol',
        Country: 'Country',
        ExchangeRate: 'Exchange Rate',
        id: 'id',
      },
    },
    PaymentMethods: {
      name: 'Payment Methods',
      fields: {
        PaymentMethodID: 'Payment Method Id',
        PaymentMethodName: 'Payment Method Name',
        Provider: 'Provider',
        AccountDetails: 'Account Details',
        UserID: 'User Id',
        ExpiryDate: 'Expiry Date',
        Status: 'Status',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    transactions: {
      name: 'Transactions (fr)',
      fields: {
        TransactionID: 'Transaction Id (fr)',
        UserID: 'User Id (fr)',
        CurrencyFrom: 'Currency From (fr)',
        CurrencyTo: 'Currency To (fr)',
        AmountSent: 'Amount Sent (fr)',
        AmountReceived: 'Amount Received (fr)',
        TransactionDate: 'Transaction Date (fr)',
        ExchangeRate: 'Exchange Rate (fr)',
        Status: 'Status (fr)',
        id: 'id',
      },
    },
    users: {
      name: 'Users (fr)',
      fields: {
        UserID: 'User Id (fr)',
        Username: 'Username (fr)',
        Email: 'Email (fr)',
        Password: 'Password (fr)',
        FullName: 'Full Name (fr)',
        RegistrationDate: 'Registration Date (fr)',
        LastLoginDate: 'Last Login Date (fr)',
        AccountStatus: 'Account Status (fr)',
        id: 'id',
      },
    },
    currencies: {
      name: 'Currencies (fr)',
      fields: {
        CurrencyID: 'Currency Id (fr)',
        CurrencyName: 'Currency Name (fr)',
        CurrencyCode: 'Currency Code (fr)',
        Symbol: 'Symbol (fr)',
        Country: 'Country (fr)',
        ExchangeRate: 'Exchange Rate (fr)',
        id: 'id',
      },
    },
    PaymentMethods: {
      name: 'Payment Methods (fr)',
      fields: {
        PaymentMethodID: 'Payment Method Id (fr)',
        PaymentMethodName: 'Payment Method Name (fr)',
        Provider: 'Provider (fr)',
        AccountDetails: 'Account Details (fr)',
        UserID: 'User Id (fr)',
        ExpiryDate: 'Expiry Date (fr)',
        Status: 'Status (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
